name: Clear Cloudflare pages cache
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Wait until the Cloudflare pages Github app completes
      # TODO: Improve this
      - name: Sleep for 30 seconds
        run: sleep 30s
        shell: bash

      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
